[package]
name = "pipviewer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.2.19"
crossbeam = "0.8.2"
crossterm = "0.25.0"